
ACTIVITY_TYPES: set[str] = {
    "art_gallery",
    "art_museum",
    "bakery",
    "bar",
    "barbecue_restaurant",
    "bistro",
    "bridge",
    "cafe",
    "cafeteria",
    "cake_shop",
    "church",
    "coffee_shop",
    "cultural_center",
    "dessert_restaurant",
    "donut_shop",
    "eastern_european_restaurant",
    "event_venue",
    "fast_food_restaurant",
    "gas_station",
    "gastropub",
    "hamburger_restaurant",
    "history_museum",
    "hotel",
    "irish_pub",
    "italian_restaurant",
    "lounge_bar",
    "meal_takeaway",
    "mosque",
    "movie_theater",
    "museum",
    "other",
    "pastry_shop",
    "pizza_restaurant",
    "playground",
    "restaurant",
    "seafood_restaurant",
    "soul_food_restaurant",
    "sushi_restaurant",
    "tourist_attraction",
    "wine_bar",
}

CONTEXT_KEYWORDS: dict[str, set[str]] = {
    "breakfast": {
        "bakery",
        "breakfast_restaurant",
        "brunch_restaurant",
        "cafe",
        "coffee_shop",
        "dessert_shop",
        "pastry_shop",
    },
    "coffee": {
        "bakery",
        "cafe",
        "coffee_shop",
        "dessert_shop",
        "pastry_shop",
    },
    "lunch": {
        "bakery",
        "barbecue_restaurant",
        "bistro",
        "cafe",
        "diner",
        "fast_food_restaurant",
        "italian_restaurant",
        "lunch_restaurant",
        "restaurant",
        "sandwich_shop",
        "seafood_restaurant",
    },
    "dinner": {
        "barbecue_restaurant",
        "bistro",
        "fine_dining_restaurant",
        "grill",
        "italian_restaurant",
        "restaurant",
        "seafood_restaurant",
        "steak_house",
        "sushi_restaurant",
    },
    "nightlife": {
        "bar",
        "cocktail_bar",
        "lounge",
        "night_club",
        "pub",
    },
    "culture": {
        "art_gallery",
        "history_museum",
        "library",
        "monument",
        "museum",
        "tourist_attraction",
    },
    "family": {
        "amusement_park",
        "bowling_alley",
        "movie_theater",
        "museum",
        "park",
        "playground",
        "zoo",
    },
    "outdoors": {
        "beach",
        "botanical_garden",
        "hiking_area",
        "lake",
        "park",
        "tourist_attraction",
    },
    "shopping": {
        "book_store",
        "clothing_store",
        "market",
        "shopping_mall",
        "supermarket",
    },
    "wellness": {
        "beauty_salon",
        "gym",
        "massage",
        "sauna",
        "spa",
    },
}

_DAY_ALIASES = {
    "0": "monday",
    "1": "tuesday",
    "2": "wednesday",
    "3": "thursday",
    "4": "friday",
    "5": "saturday",
    "6": "sunday",
}